name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: 18.x
    - run: ${{ github.action_path }}/dist/index.js
      shell: bash
