# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  apiToken:
    description: 'Cloudflare API Token'
    required: true
  accountId:
    description: 'Cloudflare Account ID'
    required: true
  projectName:
    description: 'The name of the Pages project to upload to'
    required: true
  directory:
    description: 'The directory of static files to upload'
    required: true
  githubToken:
    description: 'Github API key from the action to use. e.g ${{ secrets.GITHUB_TOKEN }}'
    required: true

outputs:
  url:
    description: 'Cloudflare Pages deployed url'
  environment:
    description: 'Cloudflare Pages deployed environment'

runs:
  using: 'node16'
  main: 'dist/index.js'
