# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: 'delete deployments'
on:
  pull_request:
    types: [opened, closed, reopened, edited]
    branches:
      - main
      - 'releases/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3.5.2
      - id: 'our-action'
        uses: ./
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'cloudflare-pages-action'
          directory: 'example/dist'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
