# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: 'delete deployments'
on:
  pull_request:
    types: [closed]
    branches:
      - main
      - 'releases/*'

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - id: 'our-action'
        uses: ./
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'cloudflare-pages-action'
          directory: 'example/dist'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
